#Z-scores for relevant products
optimal_load_sandwich_scoring: 0.2
optimal_load_dessert_scoring: 0.1
optimal_load_cola_scoring: 0.2
optimal_load_beer_scoring: 0.4

#daytime coefficient
morning_item: 1.2
noon_item: 1.2
lunch_coefficient: 1.3
afternoon_coefficient: 1.3
dinner_coefficient: 1.3
evening_coefficient: 1.1
night_coefficient: 1.3

#delay coefficients
no_delay: 0.8
short_delay: 1.3
long_delay: 1.8

#arrival coefficients
no_delay_on_arrival: 1
short_delay_on_arrival: 1.2
long_delay_on_arrival: 1.7

#country coefficient
level_1_country: 1.4
level_2_country: 1.5
level_3_country: 1.6
level_4_country: 1.7
level_5_country: 1.8

#flight lenghts
short_flight: 1.1
mid_flight: 1.2
long_flight: 1.3

#average price level on this flight
flight_median_ticket_price: 187

#average ticket prices on this route
very_cheap: 0.8
between_minimum_and_first_quartile: 0.9
under_medium_price: 1
over_medium_price: 1.1
just_under_maximum: 1.2
over_maximum: 1.3

#culture events
rank2_event: 1.017
rank3_event: 1.12
rank4_event: 1.21
rank5_event: 1.31
