-- MySQL Script generated by MySQL Workbench
-- Fri May  7 15:30:48 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sales_dwh
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sales_dwh
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sales_dwh` DEFAULT CHARACTER SET utf8 ;
USE `sales_dwh` ;

-- -----------------------------------------------------
-- Table `sales_dwh`.`flight_dwh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_dwh`.`flight_dwh` (
  `id` INT NOT NULL,
  `date` DATE NULL,
  `departure_time` DATETIME NULL,
  `arrival_time` DATETIME NULL,
  `origin` VARCHAR(3) NULL,
  `destination` VARCHAR(3) NULL,
  `flight_number` VARCHAR(6) NULL,
  `pax` INT NULL,
  `sandwich` INT NULL,
  `dessert` INT NULL,
  `cola` INT NULL,
  `beer` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;

USE `sales_dwh` ;

-- -----------------------------------------------------
-- Placeholder table for view `sales_dwh`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sales_dwh`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `sales_dwh`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sales_dwh`.`view1`;
USE `sales_dwh`;

CREATE USER 'tomas' IDENTIFIED BY 'tomas1';

GRANT ALL ON `sales_dwh`.* TO 'tomas';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
